### PR TITLE
Conflict if I do git submodule --merge

### PR DESCRIPTION
**Pull request by jeonghanlee**
Hi, 

  I have the following issues, if I do the git submodule ... --merge. It may be there are somethings missing in git repository. Please review them and let me know.

```
git submodule update --init --recursive pvCommonCPP/.
Cloning into 'pvCommonCPP'...
remote: Counting objects: 3844, done.
remote: Total 3844 (delta 0), reused 0 (delta 0), pack-reused 3844
Receiving objects: 100% (3844/3844), 4.68 MiB | 2.81 MiB/s, done.
Resolving deltas: 100% (2368/2368), done.
Checking connectivity... done.
Submodule path 'pvCommonCPP': checked out 'd0bbf47ce449f80f5c6d3e262cf6f924753aa457'
git submodule update --remote --merge pvCommonCPP/
Auto-merging mbSrc/Makefile
CONFLICT (content): Merge conflict in mbSrc/Makefile
Automatic merge failed; fix conflicts and then commit the result.
Unable to merge '26bebc9dcef3bbf5afad74cf7e8a4e6358c15a04' in submodule path 'pvCommonCPP'
```

### CODE REVIEW

**Comment by ralphlange** [comment]
pvCommonCPP is not part of EPICS 7 anymore - why do you need that module?

**Comment by jeonghanlee** [comment]
Still our current base is "3.15.5", and as you know, it is the dynamic loading and so on. I've got the many questions from people here, when our environment supports EPICS 7. So before moving to EPICS7 (I also works on this), I would like to build everything (V4) as "loadable libraries" . 

Still, pvCommon doesn't have any interesting part which I would like to add, but I would like to prepare anything, which people may ask me later here with consistent ESS EPICS Environment (e3) buidling system. :) 

This is not in EPICS 7, this is the ess building system for pvCommonCPP. We also use gitsubmodule, but we merge the latest version of that module always and don't rely on "hash" information. I guess somewhere in that repository, hash are confused by itself, because all other repositories are working fine except this. Or I did something wrong in ess environment.

**Comment by ralphlange** [comment]
Still - I would just remove it.
It contains boost for systems without boost - does not apply to Linux.
It also has some micro-benchmarking code which is disabled in all builds.

**Comment by ttkorhonen** [comment]
I agree. It was necessary at the time when the V4 modules were initially included but it does not apply to Linux or any of our systems anymore. It is safe to leave this off.

**Comment by jeonghanlee** [comment]
OK, got it. I will remove it. :)

**Pull request closed without merging**
